#!/bin/bash

set -xe  # Exit on error and print commands as they are executed

# Array of C++ source files
sources_cpp_files=(
    "source/main.cpp"
    "source/utils/window.cpp"
    "source/utils/renderer.cpp"
    "source/utils/shape.cpp"
)

# Function to compile the source files
compile() {
    g++ -o bin/engine -I thirdparty "${sources_cpp_files[@]}" -lX11 -lGL -lGLU -lGLEW
    #g++ main.cpp window.cpp renderer.cpp shape.cpp windowCreator.cpp -o engine -lX11 -lGL -lGLU
}

# Check command-line arguments
if [ "$1" = "compile" ]; then
    compile
elif [ "$1" = "run" ]; then
    # Compile first, then run the app
    compile
    ./bin/engine
else
    echo "Usage: $0 {compile|run}"
    exit 1
fi