#!/bin/bash

set -xe  # Exit on error and print commands as they are executed

# Array of C++ source files
sources_cpp_files=(
    # Sources engine
    "source/main.cpp"
    "source/utils/window.cpp"
    "source/utils/renderer.cpp"
    "source/utils/shape.cpp"
    "source/utils/camera.cpp"
    # Sources imgui
    "thirdparty/imgui/imgui.cpp"
    "thirdparty/imgui/imgui_draw.cpp"
    "thirdparty/imgui/imgui_widgets.cpp"
    "thirdparty/imgui/imgui_tables.cpp"
    "thirdparty/imgui/backends/imgui_impl_opengl3.cpp"
    "source/ventor/impl_glx.cpp"
    # Dependencies
    "thirdparty/tinyobjloader/tiny_obj_loader.cc"
    "thirdparty/stb/stb_image.c"
)

# Function to compile the source files
compile() {
    g++ -o bin/engine -I thirdparty -I source -I thirdparty/imgui -I thirdparty/tinyobjloader -I thirdparty/stb "${sources_cpp_files[@]}" -lX11 -lGL -lGLU -lGLEW
}

# Check command-line arguments
if [ "$1" = "compile" ]; then
    compile
elif [ "$1" = "run" ]; then
    # Compile first, then run the app
    compile
    ./bin/engine
else
    echo "Usage: $0 {compile|run}"
    exit 1
fi